# Site settings
title: YouthLit
email: kali@youthlit.org
description: Building Youth Literacy One Child At A Time


# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
